# Generated by Django 3.2 on 2021-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
