# Generated by Django 3.2 on 2021-05-05 20:08

import json
import os
from django.db import migrations


def load_initial_settings(apps,schema_editor):
    if schema_editor.connection.alias != 'default':
        return

    SystemSetting = apps.get_model("sitemonitor", "SystemSetting")

    file_path = os.path.abspath(
        os.path.join(
            os.path.dirname( __file__ ), '..', 'fixtures', 'initial.json'))

    with open(file_path) as f:
        settings = json.load(f) 

    for setting in settings:
        fields = setting.get('fields')

        SystemSetting.objects.get_or_create(
            key = fields.get("key"),
            label = fields.get("label"),
            value = fields.get("value"),
            value_type = fields.get("value_type"),
            deletable = fields.get("deletable"),
        )

class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0002_systemsetting_deletable'),
    ]

    operations = [
        migrations.RunPython(load_initial_settings),
    ]
